version: '3.6'
services:
  database:
    container_name: mutant-database
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mutant
      MYSQL_ROOT_PASSWORD: mutant123
      MYSQL_USER: docker
      MYSQL_PASSWORD: mutant123
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - ./.esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  web:
    container_name: mutant-api
    build: .
    ports:
      - "3000:3000"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    depends_on:
      - database
      - elasticsearch
      - kibana
    links:
      - database
      - elasticsearch
      - kibana

volumes:
  esdata:
    driver: local